// includes/admin/assets/js/speed-popover/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
        <div className="rl-node-wrapper">
            <span className="rl-icon">
                <img src="/assets/images/logo-icon-light.svg" alt=""/>
            </span>
            <span className="rl-label">RapidLoad</span>
        </div>
  );
}

export default App;

// includes/admin/frontend/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div class="rapidload-wrapper mt-12 ml-8">

    <header >

      <RouterLink to="/">
        <img alt="RapidLoad Logo" class="logo ml-4" src="@/assets/logo.svg" width="200" />
      </RouterLink>

      <div class="wrapper">

        <nav>

        </nav>
      </div>
    </header>

    <RouterView />

  </div>

</template>

<style>

</style>
